name: mame-android-build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'select branch to build(default: master)'
        required: false
        default: 'master'

jobs:
  mame_android_build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 18

    - name: Download MAME source code
      run: |
        cd ${{ github.workspace }}
        git clone --branch ${{ github.event.inputs.branch || 'master' }} https://github.com/XEnjoyForYouX/mame.git --recursive
        cd mame
        

    - id: version
      name: Get version
      run: |
        echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        cd ${{ github.workspace }}/mame
        echo "hash=$(git log -1 --pretty=format:%H)" >> $GITHUB_OUTPUT
        echo "short_hash=$(git describe --always --long)" >> $GITHUB_OUTPUT
        echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT

    - name: Set up cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/wrapper
        key: ${{ runner.os }}-mame-${{ steps.version.outputs.hash }}
        restore-keys: |
            ${{ runner.os }}-mame-

    #- name: Prepare environment
    #  run: |
    #    sudo apt-get install -y ninja-build
    #      ln -s /usr/bin/ninja .
    - name: Build Android
      run: |
        cd ${{ github.workspace }}/mame/android-project
        chmod +x ./gradlew
        ./gradlew "assembleRelease"
        # bash gradlew build
        mv $(find app/build/outputs/apk -type f | grep -E "\.apk$") ${{ github.workspace }}/mame-${{ steps.version.outputs.date }}-${{ steps.version.outputs.version }}.apk

    - name: Release mame (Mame-Android)
      uses: softprops/action-gh-release@v2
      with:
        name: mame ${{ steps.version.outputs.date }}
        tag_name: mame
        files: ${{ github.workspace }}/mame-${{ steps.version.outputs.date }}-${{ steps.version.outputs.version }}.apk

    - name: Release mame ${{ steps.version.outputs.date }}
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ steps.version.outputs.date }}
        tag_name: ${{ steps.version.outputs.date }}
        files: ${{ github.workspace }}/mame-${{ steps.version.outputs.date }}-${{ steps.version.outputs.version }}.apk
